home_assistant:
  url: "ws://your-ha-instance:8123/api/websocket"
  token: "your_long_lived_access_token"
handler:
  type: "azure"
azure:
  connection_string: "your_eventhub_connection_string"
  eventhub_name: "your_eventhub_name"
flask:
  host: "0.0.0.0"
  port: 5000
  debug: false